const TOPIC_PREFIX = 'telenot/alarm/kg/ema_zentrale'

const ema = {
    sicherungsbereich: [
        {
            hex: '0x0',
            name: 'Naegele',
            name_ha: 'Naegele',
            type: 'sicherung',
            topic: `${TOPIC_PREFIX}/sicherung1`,
            location: 'Telenot Zentrale',
            inverted: false,
        },
    ],
    sicherungsbereich2: [
        {
            hex: '0x0',
            name: 'Home',
            name_ha: 'Home Naegele',
            type: 'naegele',
            topic: `${TOPIC_PREFIX}/home_sicherung`,
            location: 'Telenot Zentrale',
            inverted: false,
        },
    ],
    meldebereiche: [
        {
            hex: '0x40',
            name: 'Unscharf',
            name_ha: 'System Unscharf',
            type: 'systemstatus',
            topic: `${TOPIC_PREFIX}/unscharf`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x41',
            name: 'Intern scharf',
            name_ha: 'System Intern Scharf',
            type: 'systemstatus',
            topic: `${TOPIC_PREFIX}/intern_scharf`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x42',
            name: 'Extern scharf',
            name_ha: 'System Extern Scharf',
            type: 'systemstatus',
            topic: `${TOPIC_PREFIX}/extern_scharf`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x43',
            name: 'Alarm',
            name_ha: 'System Alarm',
            type: 'systemstatus',
            topic: `${TOPIC_PREFIX}/alarm`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x44',
            name: 'Stoerung',
            name_ha: 'System Störung',
            type: 'systemstatus',
            topic: `${TOPIC_PREFIX}/stoerung`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x45',
            name: 'Intern Bereit',
            name_ha: 'System Intern Bereit',
            type: 'systemstatus',
            topic: `${TOPIC_PREFIX}/intern_bereit`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x46',
            name: 'Extern Bereit',
            name_ha: 'System Extern Bereit',
            type: 'systemstatus',
            topic: `${TOPIC_PREFIX}/extern_bereit`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x88',
            name: 'MK EG',
            name_ha: 'Magnetkontakt Erdgeschoss',
            type: 'magnetkontakt',
            topic: `${TOPIC_PREFIX}/mk_eg`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x89',
            name: 'SK EG',
            name_ha: 'Schliesskontakt Erdgeschoss',
            type: 'schliesskontakt',
            topic: `${TOPIC_PREFIX}/sk_eg`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x8a',
            name: 'IM EG',
            name_ha: 'Bewegungsmelder EG',
            type: 'bewegungsmelder',
            topic: `${TOPIC_PREFIX}/im_eg`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
    ],
    meldegruppen: [
        {
            hex: '0x0B7',
            name: 'Ueberfallmelder Zentrale',
            name_ha: 'Überfallmelder Zentrale',
            type: 'ueberfallmelder',
            topic: `${TOPIC_PREFIX}/ueberfallmelder`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x010',
            name: 'Zentrale Bereit',
            name_ha: 'Zentrale Bereit',
            type: 'systemstatus',
            topic: `${TOPIC_PREFIX}/zentrale_bereit`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x004',
            name: 'Sabotage MB99 Bus',
            name_ha: 'Sabotage MB99 Bus',
            type: 'sabotage',
            topic: `${TOPIC_PREFIX}/sabotage_mb99_bus`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x000',
            name: 'ESG Vorne Gehaeuse',
            name_ha: 'ESG Vorne Gehäuse',
            type: 'gehaeuse',
            topic: `${TOPIC_PREFIX}/esg_vorne_gehaeuse`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x011',
            name: 'ESG Vorne Akustisch SG',
            name_ha: 'ESG Vorne Akustisch Signalgeber',
            type: 'signalgeber',
            topic: `${TOPIC_PREFIX}/esg_vorne_akustisch_sg`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
        {
            hex: '0x013',
            name: 'ESG Vorne Optisch SG',
            name_ha: 'ESG Vorne Optisch Signalgeber',
            type: 'signalgeber',
            topic: `${TOPIC_PREFIX}/esg_vorne_optisch_sg`,
            location: 'Telenot Zentrale',
            inverted: true,
        },
    ],
}

export default ema
